<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Views\Assets\Icon_Close.png" />
    <None Remove="Views\Assets\Icon_Close_FFD3D3D3.png" />
    <None Remove="Views\Assets\Icon_Fail_FFFF0000.png" />
    <None Remove="Views\Assets\Icon_Option_FFD3D3D3.png" />
    <None Remove="Views\Assets\Icon_Pass_FF7CFC00.png" />
    <None Remove="Views\Assets\Icon_Remove_FFD3D3D3.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Management" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Views\Assets\Icon_Add_FFD3D3D3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Views\Assets\Icon_Close.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Views\Assets\Icon_Close_FFD3D3D3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Views\Assets\Icon_Fail_FFFF0000.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Views\Assets\Icon_Loading.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Views\Assets\Icon_Option_FFD3D3D3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Views\Assets\Icon_Pass_FF7CFC00.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Views\Assets\Icon_Remove_FFD3D3D3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="UMonitorSocketServer\publish\appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
